### ISSUE TITLE
Frankenstein using an old InternalBlue Version?

### ISSUE THREAD

**Issue by MrMatch246** [seemoo-lab/frankenstein#7]
I tried using the internalBlueMod.py and got following error:
`Traceback (most recent call last):
  File "/home/user/frankenstein/internalBlueMod.py", line 1, in <module>
    import internalblue.cmds
ModuleNotFoundError: No module named 'internalblue.cmds'
`
I researched that error and found out that in a previous version of internalblue there was a file cmds.py and a class Cmd that was removed when converting form pwntool to cmd2 for cmd-handling (i guess).
Is this easy to fix and if not which is the latest working commit?

Greetings.

**Comment by jiska2342** [comment]
Oh, you're right, we switched to `cmd2` recently. Should be easy to switch but didn't try it yet. @unixb0y added the ports to `cmd2`, so I guess this one here could be one of the latest working commits: https://github.com/seemoo-lab/internalblue/commit/68f4a7ef0a76c37c85062533c48be44071e77f7d

I'll do some Frankenstein-related stuff in probably 2-3 weeks and will see if I can fix the root cause :)

**Comment by unixb0y** [comment]
I'll try fixing the script later :)

**Comment by Boogboy** [comment]
Hi, is there a workaround available in the meantime while this is being fixed? Thanks for your work. :)

**Comment by bolek42** [comment]
Hi,
I'm half way through the fix. The interalblue API changed quite a bit so porting was not to straight forward. I gues a valid hotfix would be to use an old version of InternalBlue without cmd2.
Sorry for the inconvenience, I'll try to push the fix this week.

**Comment by bolek42** [comment]
I've pushed some changes that fix most of this issue. loadelf and xmitstate should work now again however, there is still a bug with mapmemory that I do not understand right now.
I also stumbled across some other bugs, especially one in xmitstate. get_int and set_int from xmit_memory.patch caused an illegal instruction as they were not disabled using patch_return()

**Comment by jiska2342** [comment]
Tested it on my machine and `loadelf` also works for me :)
